### PR TITLE
Include uk/config.h in ngx_auto_config.h

### LINKED ISSUE #11: The build breaks with undefined `NGX_HTTP_V2_ENCODE_HUFF` and `NGX_HTTP_V2_ENCODE_RAW`.
When building the application with [Musl](), it gives this error:
```make
gbuild/libnginx/origin/nginx-1.15.6/src/http/v2/ngx_http_v2_encode.c:23:12: warning: implicit declaration of function ‘ngx_http_v2_huff_encode’; did you mean ‘ngx_http_v2_string_encode’? [-Wimplicit-function-declaration]                                                                                                                                          
   23 |     hlen = ngx_http_v2_huff_encode(src, len, tmp, lower);                                                                                                                                                  
      |            ^~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                         
      |            ngx_http_v2_string_encode                                                                                                                                                                       
gbuild/libnginx/origin/nginx-1.15.6/src/http/v2/ngx_http_v2_encode.c:26:16: error: ‘NGX_HTTP_V2_ENCODE_HUFF’ undeclared (first use in this function)                                                                                                                                                                                                                  
   26 |         *dst = NGX_HTTP_V2_ENCODE_HUFF;                                                                                                                                                                    
      |                ^~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                     
gbuild/libnginx/origin/nginx-1.15.6/src/http/v2/ngx_http_v2_encode.c:26:16: note: each undeclared identifier is reported only once for each function it appears in                                                                                                                                                                                                    
gbuild/libnginx/origin/nginx-1.15.6/src/http/v2/ngx_http_v2_encode.c:27:42: warning: implicit declaration of function ‘ngx_http_v2_prefix’; did you mean ‘ngx_http_v2_write_int’? [-Wimplicit-function-declaration]                                                                                                                                                   
   27 |         dst = ngx_http_v2_write_int(dst, ngx_http_v2_prefix(7), hlen);                                                                                                                                     
      |                                          ^~~~~~~~~~~~~~~~~~                                                                                                                                                
      |                                          ngx_http_v2_write_int                                                                                                                                             
gbuild/libnginx/origin/nginx-1.15.6/src/http/v2/ngx_http_v2_encode.c:31:12: error: ‘NGX_HTTP_V2_ENCODE_RAW’ undeclared (first use in this function; did you mean ‘NGX_HTTP_V2_BUFFERED’?                                                                                                                                                                             
   31 |     *dst = NGX_HTTP_V2_ENCODE_RAW;                                                                                                                                                                         
      |            ^~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                          
      |            NGX_HTTP_V2_BUFFERED
```

Config options:
* `LIBMUSL`
* `LIBNGINX`
* `LIBLWIP`
* `LIBNGINX_HTTP`

Note: Musl does not work with `uksignal` at the moment, so you will need to disable that.

### PR DESCRIPTION
**Pull request by razvand**
This fix gets Musl-based Nginx build to work.

### CODE REVIEW

**Review by StefanJum — APPROVED** [review]
All good here.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by craciunoiuc — CHANGES_REQUESTED** [review]
Hey @razvand

I would change the commit message like this, because the file in the name is redundant
`Include uk/config.h in ngx_auto_config.h` -> `include: Include uk/config.h`

Optional:

As we are touching this file, I was going to ask if we should also update #L20
`#define NGX_COMPILER "gcc 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) "`

Not sure if it does something, but maybe we should bump it to at least `10`

**Comment by razvand** [comment]
@craciunoiuc , I applied your comments.

**Review by craciunoiuc — APPROVED** [review]
All good here. Thanks!

Approved-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

**Pull request closed without merging**
